---
abstract: 'utilities for doing common async operations'
author:
  - 'Whitney Jackson <whitney@cpan.org>'
build_requires:
  AnyEvent: 0
  List::MoreUtils: 0
  Test::More: 0
  ok: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300023, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Async-Util
requires:
  Carp: 0
  Exporter: 0
  Scalar::Util: 0
  perl: v5.10.0
  strict: 0
  warnings: 0
version: 0.01
